# Change these first
owner: TuxTechLab # GitHub organization or username, where this repository lives
repo: up # The name of this repository

sites:
  # Actual Websites
  - name: Google
    url: https://www.google.com
  - name: GitHub
    url: https://www.github.com
  # Social Pages
  - name: LinkTree
    url: https://linktr.ee
  - name: LinkTree Admin Dashboard
    url: https://linktr.ee/arindamtanti
  # Test Broken Websites
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /up
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: up
  introTitle: "[**Up**](https://tuxtechlab.github.io/up/) is the uptime monitor and status page, powered entirely by GitHub powered by [**Upptime**](https://github.com/upptime/upptime)."
  introMessage: A sample status page which uses **real-time** data from our [GitHub repository](https://github.com/tuxtechlab/up). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
